name: Fastly Compute Branch Previews
concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.workflow}}
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - uses: fastly/compute-actions/preview@a25cf83ef5c19ef7d86f1eebffcd8f6c02ddc786 # v14
        with:
          fastly-api-token: ${{ secrets.FASTLY_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
